apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: y0kps23da-go-gitops
  description: This is GitOps manifest for y0kps23da-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: y0kps23da-go
    janus-idp.io/tekton: y0kps23da-go
    backstage.io/kubernetes-id: y0kps23da-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:y0kps23da-go
